# Generated by Django 4.2.16 on 2025-11-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexoapp', '0002_alter_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logventa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='logventa',
            name='venta',
        ),
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='nexoapp_pro_nombre_aaf745_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='nexoapp_pro_categor_2c17a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='nexoapp_pro_estado_91822d_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='nexoapp_ven_estado_6f64a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='nexoapp_ven_fecha_c_6651c5_idx',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='valoracion',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='impuestos',
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='LogVenta',
        ),
    ]
