# Generated by Django 4.2.16 on 2025-11-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexoapp', '0003_remove_logventa_usuario_remove_logventa_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='suscripcion',
        ),
        migrations.CreateModel(
            name='CompraSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('pendiente_pago', 'Pendiente de Pago'), ('renovada', 'Renovada')], default='activa', max_length=20)),
                ('monto_pagado', models.IntegerField()),
                ('metodo_pago', models.CharField(blank=True, help_text='Método de pago utilizado', max_length=50)),
                ('id_transaccion', models.CharField(blank=True, max_length=100, unique=True)),
                ('notas', models.TextField(blank=True)),
                ('es_renovacion', models.BooleanField(default=False)),
                ('compra_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='nexoapp.comprasuscripcion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_suscripcion', to='nexoapp.proveedor')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexoapp.suscripcion')),
            ],
            options={
                'verbose_name': 'Compra de Suscripción',
                'verbose_name_plural': 'Compras de Suscripciones',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
